apiVersion: v1
kind: Pod
metadata:
  name: regservice.example.com
  labels:
    app: regservice
spec:
  containers:
  - name: regservice-1
    image: cybersmithio/regservice
    ports:
    - name: regserviceport
      containerPort: 443
  - name: regservice-mongo-1
    image: mongo
    ports:
    - name: regservicemongoport
      containerPort: 27017